// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: curp.proto
#ifndef GRPC_curp_2eproto__INCLUDED
#define GRPC_curp_2eproto__INCLUDED

#include "curp.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace curp {

// CURP 服务 - Master 端
class CurpService final {
 public:
  static constexpr char const* service_full_name() {
    return "curp.CurpService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 客户端提交操作
    virtual ::grpc::Status Propose(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::curp::ProposeReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::ProposeReply>> AsyncPropose(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::ProposeReply>>(AsyncProposeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::ProposeReply>> PrepareAsyncPropose(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::ProposeReply>>(PrepareAsyncProposeRaw(context, request, cq));
    }
    // 读操作
    virtual ::grpc::Status Read(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::curp::ReadReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::ReadReply>> AsyncRead(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::ReadReply>>(AsyncReadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::ReadReply>> PrepareAsyncRead(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::ReadReply>>(PrepareAsyncReadRaw(context, request, cq));
    }
    // 同步请求
    virtual ::grpc::Status Sync(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::curp::SyncReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::SyncReply>> AsyncSync(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::SyncReply>>(AsyncSyncRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::SyncReply>> PrepareAsyncSync(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::SyncReply>>(PrepareAsyncSyncRaw(context, request, cq));
    }
    // 恢复请求（从 Witness 获取数据）
    virtual ::grpc::Status Recover(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::curp::RecoverReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::RecoverReply>> AsyncRecover(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::RecoverReply>>(AsyncRecoverRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::RecoverReply>> PrepareAsyncRecover(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::curp::RecoverReply>>(PrepareAsyncRecoverRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 客户端提交操作
      virtual void Propose(::grpc::ClientContext* context, const ::curp::ProposeRequest* request, ::curp::ProposeReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Propose(::grpc::ClientContext* context, const ::curp::ProposeRequest* request, ::curp::ProposeReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 读操作
      virtual void Read(::grpc::ClientContext* context, const ::curp::ReadRequest* request, ::curp::ReadReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Read(::grpc::ClientContext* context, const ::curp::ReadRequest* request, ::curp::ReadReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 同步请求
      virtual void Sync(::grpc::ClientContext* context, const ::curp::SyncRequest* request, ::curp::SyncReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Sync(::grpc::ClientContext* context, const ::curp::SyncRequest* request, ::curp::SyncReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 恢复请求（从 Witness 获取数据）
      virtual void Recover(::grpc::ClientContext* context, const ::curp::RecoverRequest* request, ::curp::RecoverReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Recover(::grpc::ClientContext* context, const ::curp::RecoverRequest* request, ::curp::RecoverReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::curp::ProposeReply>* AsyncProposeRaw(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::curp::ProposeReply>* PrepareAsyncProposeRaw(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::curp::ReadReply>* AsyncReadRaw(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::curp::ReadReply>* PrepareAsyncReadRaw(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::curp::SyncReply>* AsyncSyncRaw(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::curp::SyncReply>* PrepareAsyncSyncRaw(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::curp::RecoverReply>* AsyncRecoverRaw(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::curp::RecoverReply>* PrepareAsyncRecoverRaw(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Propose(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::curp::ProposeReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::ProposeReply>> AsyncPropose(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::ProposeReply>>(AsyncProposeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::ProposeReply>> PrepareAsyncPropose(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::ProposeReply>>(PrepareAsyncProposeRaw(context, request, cq));
    }
    ::grpc::Status Read(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::curp::ReadReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::ReadReply>> AsyncRead(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::ReadReply>>(AsyncReadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::ReadReply>> PrepareAsyncRead(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::ReadReply>>(PrepareAsyncReadRaw(context, request, cq));
    }
    ::grpc::Status Sync(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::curp::SyncReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::SyncReply>> AsyncSync(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::SyncReply>>(AsyncSyncRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::SyncReply>> PrepareAsyncSync(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::SyncReply>>(PrepareAsyncSyncRaw(context, request, cq));
    }
    ::grpc::Status Recover(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::curp::RecoverReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::RecoverReply>> AsyncRecover(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::RecoverReply>>(AsyncRecoverRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::RecoverReply>> PrepareAsyncRecover(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::curp::RecoverReply>>(PrepareAsyncRecoverRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Propose(::grpc::ClientContext* context, const ::curp::ProposeRequest* request, ::curp::ProposeReply* response, std::function<void(::grpc::Status)>) override;
      void Propose(::grpc::ClientContext* context, const ::curp::ProposeRequest* request, ::curp::ProposeReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Read(::grpc::ClientContext* context, const ::curp::ReadRequest* request, ::curp::ReadReply* response, std::function<void(::grpc::Status)>) override;
      void Read(::grpc::ClientContext* context, const ::curp::ReadRequest* request, ::curp::ReadReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Sync(::grpc::ClientContext* context, const ::curp::SyncRequest* request, ::curp::SyncReply* response, std::function<void(::grpc::Status)>) override;
      void Sync(::grpc::ClientContext* context, const ::curp::SyncRequest* request, ::curp::SyncReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Recover(::grpc::ClientContext* context, const ::curp::RecoverRequest* request, ::curp::RecoverReply* response, std::function<void(::grpc::Status)>) override;
      void Recover(::grpc::ClientContext* context, const ::curp::RecoverRequest* request, ::curp::RecoverReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::curp::ProposeReply>* AsyncProposeRaw(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::curp::ProposeReply>* PrepareAsyncProposeRaw(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::curp::ReadReply>* AsyncReadRaw(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::curp::ReadReply>* PrepareAsyncReadRaw(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::curp::SyncReply>* AsyncSyncRaw(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::curp::SyncReply>* PrepareAsyncSyncRaw(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::curp::RecoverReply>* AsyncRecoverRaw(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::curp::RecoverReply>* PrepareAsyncRecoverRaw(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Propose_;
    const ::grpc::internal::RpcMethod rpcmethod_Read_;
    const ::grpc::internal::RpcMethod rpcmethod_Sync_;
    const ::grpc::internal::RpcMethod rpcmethod_Recover_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 客户端提交操作
    virtual ::grpc::Status Propose(::grpc::ServerContext* context, const ::curp::ProposeRequest* request, ::curp::ProposeReply* response);
    // 读操作
    virtual ::grpc::Status Read(::grpc::ServerContext* context, const ::curp::ReadRequest* request, ::curp::ReadReply* response);
    // 同步请求
    virtual ::grpc::Status Sync(::grpc::ServerContext* context, const ::curp::SyncRequest* request, ::curp::SyncReply* response);
    // 恢复请求（从 Witness 获取数据）
    virtual ::grpc::Status Recover(::grpc::ServerContext* context, const ::curp::RecoverRequest* request, ::curp::RecoverReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Propose() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::curp::ProposeRequest* /*request*/, ::curp::ProposeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPropose(::grpc::ServerContext* context, ::curp::ProposeRequest* request, ::grpc::ServerAsyncResponseWriter< ::curp::ProposeReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Read : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Read() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Read() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Read(::grpc::ServerContext* /*context*/, const ::curp::ReadRequest* /*request*/, ::curp::ReadReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRead(::grpc::ServerContext* context, ::curp::ReadRequest* request, ::grpc::ServerAsyncResponseWriter< ::curp::ReadReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Sync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Sync() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Sync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sync(::grpc::ServerContext* /*context*/, const ::curp::SyncRequest* /*request*/, ::curp::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSync(::grpc::ServerContext* context, ::curp::SyncRequest* request, ::grpc::ServerAsyncResponseWriter< ::curp::SyncReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Recover : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Recover() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Recover() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recover(::grpc::ServerContext* /*context*/, const ::curp::RecoverRequest* /*request*/, ::curp::RecoverReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecover(::grpc::ServerContext* context, ::curp::RecoverRequest* request, ::grpc::ServerAsyncResponseWriter< ::curp::RecoverReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Propose<WithAsyncMethod_Read<WithAsyncMethod_Sync<WithAsyncMethod_Recover<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Propose() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::curp::ProposeRequest, ::curp::ProposeReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::curp::ProposeRequest* request, ::curp::ProposeReply* response) { return this->Propose(context, request, response); }));}
    void SetMessageAllocatorFor_Propose(
        ::grpc::MessageAllocator< ::curp::ProposeRequest, ::curp::ProposeReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::curp::ProposeRequest, ::curp::ProposeReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::curp::ProposeRequest* /*request*/, ::curp::ProposeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Propose(
      ::grpc::CallbackServerContext* /*context*/, const ::curp::ProposeRequest* /*request*/, ::curp::ProposeReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Read : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Read() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::curp::ReadRequest, ::curp::ReadReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::curp::ReadRequest* request, ::curp::ReadReply* response) { return this->Read(context, request, response); }));}
    void SetMessageAllocatorFor_Read(
        ::grpc::MessageAllocator< ::curp::ReadRequest, ::curp::ReadReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::curp::ReadRequest, ::curp::ReadReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Read() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Read(::grpc::ServerContext* /*context*/, const ::curp::ReadRequest* /*request*/, ::curp::ReadReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Read(
      ::grpc::CallbackServerContext* /*context*/, const ::curp::ReadRequest* /*request*/, ::curp::ReadReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Sync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Sync() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::curp::SyncRequest, ::curp::SyncReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::curp::SyncRequest* request, ::curp::SyncReply* response) { return this->Sync(context, request, response); }));}
    void SetMessageAllocatorFor_Sync(
        ::grpc::MessageAllocator< ::curp::SyncRequest, ::curp::SyncReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::curp::SyncRequest, ::curp::SyncReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Sync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sync(::grpc::ServerContext* /*context*/, const ::curp::SyncRequest* /*request*/, ::curp::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Sync(
      ::grpc::CallbackServerContext* /*context*/, const ::curp::SyncRequest* /*request*/, ::curp::SyncReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Recover : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Recover() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::curp::RecoverRequest, ::curp::RecoverReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::curp::RecoverRequest* request, ::curp::RecoverReply* response) { return this->Recover(context, request, response); }));}
    void SetMessageAllocatorFor_Recover(
        ::grpc::MessageAllocator< ::curp::RecoverRequest, ::curp::RecoverReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::curp::RecoverRequest, ::curp::RecoverReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Recover() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recover(::grpc::ServerContext* /*context*/, const ::curp::RecoverRequest* /*request*/, ::curp::RecoverReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Recover(
      ::grpc::CallbackServerContext* /*context*/, const ::curp::RecoverRequest* /*request*/, ::curp::RecoverReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Propose<WithCallbackMethod_Read<WithCallbackMethod_Sync<WithCallbackMethod_Recover<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Propose() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::curp::ProposeRequest* /*request*/, ::curp::ProposeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Read : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Read() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Read() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Read(::grpc::ServerContext* /*context*/, const ::curp::ReadRequest* /*request*/, ::curp::ReadReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Sync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Sync() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Sync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sync(::grpc::ServerContext* /*context*/, const ::curp::SyncRequest* /*request*/, ::curp::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Recover : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Recover() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Recover() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recover(::grpc::ServerContext* /*context*/, const ::curp::RecoverRequest* /*request*/, ::curp::RecoverReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Propose() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::curp::ProposeRequest* /*request*/, ::curp::ProposeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPropose(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Read : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Read() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Read() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Read(::grpc::ServerContext* /*context*/, const ::curp::ReadRequest* /*request*/, ::curp::ReadReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRead(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Sync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Sync() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Sync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sync(::grpc::ServerContext* /*context*/, const ::curp::SyncRequest* /*request*/, ::curp::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSync(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Recover : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Recover() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Recover() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recover(::grpc::ServerContext* /*context*/, const ::curp::RecoverRequest* /*request*/, ::curp::RecoverReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecover(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Propose() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Propose(context, request, response); }));
    }
    ~WithRawCallbackMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::curp::ProposeRequest* /*request*/, ::curp::ProposeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Propose(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Read : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Read() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Read(context, request, response); }));
    }
    ~WithRawCallbackMethod_Read() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Read(::grpc::ServerContext* /*context*/, const ::curp::ReadRequest* /*request*/, ::curp::ReadReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Read(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Sync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Sync() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Sync(context, request, response); }));
    }
    ~WithRawCallbackMethod_Sync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sync(::grpc::ServerContext* /*context*/, const ::curp::SyncRequest* /*request*/, ::curp::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Sync(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Recover : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Recover() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Recover(context, request, response); }));
    }
    ~WithRawCallbackMethod_Recover() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recover(::grpc::ServerContext* /*context*/, const ::curp::RecoverRequest* /*request*/, ::curp::RecoverReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Recover(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Propose() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::curp::ProposeRequest, ::curp::ProposeReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::curp::ProposeRequest, ::curp::ProposeReply>* streamer) {
                       return this->StreamedPropose(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::curp::ProposeRequest* /*request*/, ::curp::ProposeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPropose(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::curp::ProposeRequest,::curp::ProposeReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Read : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Read() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::curp::ReadRequest, ::curp::ReadReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::curp::ReadRequest, ::curp::ReadReply>* streamer) {
                       return this->StreamedRead(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Read() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Read(::grpc::ServerContext* /*context*/, const ::curp::ReadRequest* /*request*/, ::curp::ReadReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRead(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::curp::ReadRequest,::curp::ReadReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Sync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Sync() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::curp::SyncRequest, ::curp::SyncReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::curp::SyncRequest, ::curp::SyncReply>* streamer) {
                       return this->StreamedSync(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Sync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Sync(::grpc::ServerContext* /*context*/, const ::curp::SyncRequest* /*request*/, ::curp::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSync(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::curp::SyncRequest,::curp::SyncReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Recover : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Recover() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::curp::RecoverRequest, ::curp::RecoverReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::curp::RecoverRequest, ::curp::RecoverReply>* streamer) {
                       return this->StreamedRecover(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Recover() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Recover(::grpc::ServerContext* /*context*/, const ::curp::RecoverRequest* /*request*/, ::curp::RecoverReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecover(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::curp::RecoverRequest,::curp::RecoverReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Propose<WithStreamedUnaryMethod_Read<WithStreamedUnaryMethod_Sync<WithStreamedUnaryMethod_Recover<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Propose<WithStreamedUnaryMethod_Read<WithStreamedUnaryMethod_Sync<WithStreamedUnaryMethod_Recover<Service > > > > StreamedService;
};

}  // namespace curp


#endif  // GRPC_curp_2eproto__INCLUDED
