// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: curp.proto

#include "curp.pb.h"
#include "curp.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace curp {

static const char* CurpService_method_names[] = {
  "/curp.CurpService/Propose",
  "/curp.CurpService/Read",
  "/curp.CurpService/Sync",
  "/curp.CurpService/Recover",
};

std::unique_ptr< CurpService::Stub> CurpService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CurpService::Stub> stub(new CurpService::Stub(channel, options));
  return stub;
}

CurpService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Propose_(CurpService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Read_(CurpService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Sync_(CurpService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Recover_(CurpService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CurpService::Stub::Propose(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::curp::ProposeReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::curp::ProposeRequest, ::curp::ProposeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Propose_, context, request, response);
}

void CurpService::Stub::async::Propose(::grpc::ClientContext* context, const ::curp::ProposeRequest* request, ::curp::ProposeReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::curp::ProposeRequest, ::curp::ProposeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Propose_, context, request, response, std::move(f));
}

void CurpService::Stub::async::Propose(::grpc::ClientContext* context, const ::curp::ProposeRequest* request, ::curp::ProposeReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Propose_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::curp::ProposeReply>* CurpService::Stub::PrepareAsyncProposeRaw(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::curp::ProposeReply, ::curp::ProposeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Propose_, context, request);
}

::grpc::ClientAsyncResponseReader< ::curp::ProposeReply>* CurpService::Stub::AsyncProposeRaw(::grpc::ClientContext* context, const ::curp::ProposeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProposeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CurpService::Stub::Read(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::curp::ReadReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::curp::ReadRequest, ::curp::ReadReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Read_, context, request, response);
}

void CurpService::Stub::async::Read(::grpc::ClientContext* context, const ::curp::ReadRequest* request, ::curp::ReadReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::curp::ReadRequest, ::curp::ReadReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Read_, context, request, response, std::move(f));
}

void CurpService::Stub::async::Read(::grpc::ClientContext* context, const ::curp::ReadRequest* request, ::curp::ReadReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Read_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::curp::ReadReply>* CurpService::Stub::PrepareAsyncReadRaw(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::curp::ReadReply, ::curp::ReadRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Read_, context, request);
}

::grpc::ClientAsyncResponseReader< ::curp::ReadReply>* CurpService::Stub::AsyncReadRaw(::grpc::ClientContext* context, const ::curp::ReadRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CurpService::Stub::Sync(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::curp::SyncReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::curp::SyncRequest, ::curp::SyncReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Sync_, context, request, response);
}

void CurpService::Stub::async::Sync(::grpc::ClientContext* context, const ::curp::SyncRequest* request, ::curp::SyncReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::curp::SyncRequest, ::curp::SyncReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sync_, context, request, response, std::move(f));
}

void CurpService::Stub::async::Sync(::grpc::ClientContext* context, const ::curp::SyncRequest* request, ::curp::SyncReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sync_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::curp::SyncReply>* CurpService::Stub::PrepareAsyncSyncRaw(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::curp::SyncReply, ::curp::SyncRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Sync_, context, request);
}

::grpc::ClientAsyncResponseReader< ::curp::SyncReply>* CurpService::Stub::AsyncSyncRaw(::grpc::ClientContext* context, const ::curp::SyncRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSyncRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CurpService::Stub::Recover(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::curp::RecoverReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::curp::RecoverRequest, ::curp::RecoverReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Recover_, context, request, response);
}

void CurpService::Stub::async::Recover(::grpc::ClientContext* context, const ::curp::RecoverRequest* request, ::curp::RecoverReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::curp::RecoverRequest, ::curp::RecoverReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Recover_, context, request, response, std::move(f));
}

void CurpService::Stub::async::Recover(::grpc::ClientContext* context, const ::curp::RecoverRequest* request, ::curp::RecoverReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Recover_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::curp::RecoverReply>* CurpService::Stub::PrepareAsyncRecoverRaw(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::curp::RecoverReply, ::curp::RecoverRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Recover_, context, request);
}

::grpc::ClientAsyncResponseReader< ::curp::RecoverReply>* CurpService::Stub::AsyncRecoverRaw(::grpc::ClientContext* context, const ::curp::RecoverRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRecoverRaw(context, request, cq);
  result->StartCall();
  return result;
}

CurpService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CurpService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CurpService::Service, ::curp::ProposeRequest, ::curp::ProposeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CurpService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::curp::ProposeRequest* req,
             ::curp::ProposeReply* resp) {
               return service->Propose(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CurpService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CurpService::Service, ::curp::ReadRequest, ::curp::ReadReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CurpService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::curp::ReadRequest* req,
             ::curp::ReadReply* resp) {
               return service->Read(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CurpService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CurpService::Service, ::curp::SyncRequest, ::curp::SyncReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CurpService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::curp::SyncRequest* req,
             ::curp::SyncReply* resp) {
               return service->Sync(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CurpService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CurpService::Service, ::curp::RecoverRequest, ::curp::RecoverReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CurpService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::curp::RecoverRequest* req,
             ::curp::RecoverReply* resp) {
               return service->Recover(ctx, req, resp);
             }, this)));
}

CurpService::Service::~Service() {
}

::grpc::Status CurpService::Service::Propose(::grpc::ServerContext* context, const ::curp::ProposeRequest* request, ::curp::ProposeReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CurpService::Service::Read(::grpc::ServerContext* context, const ::curp::ReadRequest* request, ::curp::ReadReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CurpService::Service::Sync(::grpc::ServerContext* context, const ::curp::SyncRequest* request, ::curp::SyncReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CurpService::Service::Recover(::grpc::ServerContext* context, const ::curp::RecoverRequest* request, ::curp::RecoverReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace curp

