// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: witness.proto

#include "witness.pb.h"
#include "witness.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace witness {

static const char* WitnessService_method_names[] = {
  "/witness.WitnessService/Record",
  "/witness.WitnessService/GarbageCollect",
  "/witness.WitnessService/GetRecoveryData",
  "/witness.WitnessService/Stop",
  "/witness.WitnessService/Reset",
  "/witness.WitnessService/GetStatus",
};

std::unique_ptr< WitnessService::Stub> WitnessService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WitnessService::Stub> stub(new WitnessService::Stub(channel, options));
  return stub;
}

WitnessService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Record_(WitnessService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GarbageCollect_(WitnessService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRecoveryData_(WitnessService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Stop_(WitnessService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Reset_(WitnessService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStatus_(WitnessService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WitnessService::Stub::Record(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::witness::RecordReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::witness::RecordRequest, ::witness::RecordReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Record_, context, request, response);
}

void WitnessService::Stub::async::Record(::grpc::ClientContext* context, const ::witness::RecordRequest* request, ::witness::RecordReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::witness::RecordRequest, ::witness::RecordReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Record_, context, request, response, std::move(f));
}

void WitnessService::Stub::async::Record(::grpc::ClientContext* context, const ::witness::RecordRequest* request, ::witness::RecordReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Record_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::witness::RecordReply>* WitnessService::Stub::PrepareAsyncRecordRaw(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::witness::RecordReply, ::witness::RecordRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Record_, context, request);
}

::grpc::ClientAsyncResponseReader< ::witness::RecordReply>* WitnessService::Stub::AsyncRecordRaw(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRecordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WitnessService::Stub::GarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::witness::GCReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::witness::GCRequest, ::witness::GCReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GarbageCollect_, context, request, response);
}

void WitnessService::Stub::async::GarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest* request, ::witness::GCReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::witness::GCRequest, ::witness::GCReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GarbageCollect_, context, request, response, std::move(f));
}

void WitnessService::Stub::async::GarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest* request, ::witness::GCReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GarbageCollect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::witness::GCReply>* WitnessService::Stub::PrepareAsyncGarbageCollectRaw(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::witness::GCReply, ::witness::GCRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GarbageCollect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::witness::GCReply>* WitnessService::Stub::AsyncGarbageCollectRaw(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGarbageCollectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WitnessService::Stub::GetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::witness::RecoveryData* response) {
  return ::grpc::internal::BlockingUnaryCall< ::witness::RecoveryRequest, ::witness::RecoveryData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRecoveryData_, context, request, response);
}

void WitnessService::Stub::async::GetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest* request, ::witness::RecoveryData* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::witness::RecoveryRequest, ::witness::RecoveryData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRecoveryData_, context, request, response, std::move(f));
}

void WitnessService::Stub::async::GetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest* request, ::witness::RecoveryData* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRecoveryData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::witness::RecoveryData>* WitnessService::Stub::PrepareAsyncGetRecoveryDataRaw(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::witness::RecoveryData, ::witness::RecoveryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRecoveryData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::witness::RecoveryData>* WitnessService::Stub::AsyncGetRecoveryDataRaw(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRecoveryDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WitnessService::Stub::Stop(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::witness::StopReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::witness::StopRequest, ::witness::StopReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Stop_, context, request, response);
}

void WitnessService::Stub::async::Stop(::grpc::ClientContext* context, const ::witness::StopRequest* request, ::witness::StopReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::witness::StopRequest, ::witness::StopReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Stop_, context, request, response, std::move(f));
}

void WitnessService::Stub::async::Stop(::grpc::ClientContext* context, const ::witness::StopRequest* request, ::witness::StopReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Stop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::witness::StopReply>* WitnessService::Stub::PrepareAsyncStopRaw(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::witness::StopReply, ::witness::StopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Stop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::witness::StopReply>* WitnessService::Stub::AsyncStopRaw(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WitnessService::Stub::Reset(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::witness::ResetReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::witness::ResetRequest, ::witness::ResetReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Reset_, context, request, response);
}

void WitnessService::Stub::async::Reset(::grpc::ClientContext* context, const ::witness::ResetRequest* request, ::witness::ResetReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::witness::ResetRequest, ::witness::ResetReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Reset_, context, request, response, std::move(f));
}

void WitnessService::Stub::async::Reset(::grpc::ClientContext* context, const ::witness::ResetRequest* request, ::witness::ResetReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Reset_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::witness::ResetReply>* WitnessService::Stub::PrepareAsyncResetRaw(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::witness::ResetReply, ::witness::ResetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Reset_, context, request);
}

::grpc::ClientAsyncResponseReader< ::witness::ResetReply>* WitnessService::Stub::AsyncResetRaw(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncResetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WitnessService::Stub::GetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::witness::StatusReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::witness::StatusRequest, ::witness::StatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStatus_, context, request, response);
}

void WitnessService::Stub::async::GetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest* request, ::witness::StatusReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::witness::StatusRequest, ::witness::StatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, std::move(f));
}

void WitnessService::Stub::async::GetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest* request, ::witness::StatusReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::witness::StatusReply>* WitnessService::Stub::PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::witness::StatusReply, ::witness::StatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::witness::StatusReply>* WitnessService::Stub::AsyncGetStatusRaw(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

WitnessService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WitnessService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WitnessService::Service, ::witness::RecordRequest, ::witness::RecordReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WitnessService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::witness::RecordRequest* req,
             ::witness::RecordReply* resp) {
               return service->Record(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WitnessService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WitnessService::Service, ::witness::GCRequest, ::witness::GCReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WitnessService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::witness::GCRequest* req,
             ::witness::GCReply* resp) {
               return service->GarbageCollect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WitnessService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WitnessService::Service, ::witness::RecoveryRequest, ::witness::RecoveryData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WitnessService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::witness::RecoveryRequest* req,
             ::witness::RecoveryData* resp) {
               return service->GetRecoveryData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WitnessService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WitnessService::Service, ::witness::StopRequest, ::witness::StopReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WitnessService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::witness::StopRequest* req,
             ::witness::StopReply* resp) {
               return service->Stop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WitnessService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WitnessService::Service, ::witness::ResetRequest, ::witness::ResetReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WitnessService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::witness::ResetRequest* req,
             ::witness::ResetReply* resp) {
               return service->Reset(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WitnessService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WitnessService::Service, ::witness::StatusRequest, ::witness::StatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WitnessService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::witness::StatusRequest* req,
             ::witness::StatusReply* resp) {
               return service->GetStatus(ctx, req, resp);
             }, this)));
}

WitnessService::Service::~Service() {
}

::grpc::Status WitnessService::Service::Record(::grpc::ServerContext* context, const ::witness::RecordRequest* request, ::witness::RecordReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WitnessService::Service::GarbageCollect(::grpc::ServerContext* context, const ::witness::GCRequest* request, ::witness::GCReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WitnessService::Service::GetRecoveryData(::grpc::ServerContext* context, const ::witness::RecoveryRequest* request, ::witness::RecoveryData* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WitnessService::Service::Stop(::grpc::ServerContext* context, const ::witness::StopRequest* request, ::witness::StopReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WitnessService::Service::Reset(::grpc::ServerContext* context, const ::witness::ResetRequest* request, ::witness::ResetReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WitnessService::Service::GetStatus(::grpc::ServerContext* context, const ::witness::StatusRequest* request, ::witness::StatusReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace witness

