// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: witness.proto
#ifndef GRPC_witness_2eproto__INCLUDED
#define GRPC_witness_2eproto__INCLUDED

#include "witness.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace witness {

// Witness 服务 - 用于 CURP 协议中的无序持久化
// Witness 只存储请求，不参与排序
class WitnessService final {
 public:
  static constexpr char const* service_full_name() {
    return "witness.WitnessService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 客户端记录请求到 Witness
    virtual ::grpc::Status Record(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::witness::RecordReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::RecordReply>> AsyncRecord(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::RecordReply>>(AsyncRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::RecordReply>> PrepareAsyncRecord(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::RecordReply>>(PrepareAsyncRecordRaw(context, request, cq));
    }
    // Master 垃圾回收已同步的请求
    virtual ::grpc::Status GarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::witness::GCReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::GCReply>> AsyncGarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::GCReply>>(AsyncGarbageCollectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::GCReply>> PrepareAsyncGarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::GCReply>>(PrepareAsyncGarbageCollectRaw(context, request, cq));
    }
    // 恢复时获取所有记录的请求
    virtual ::grpc::Status GetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::witness::RecoveryData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::RecoveryData>> AsyncGetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::RecoveryData>>(AsyncGetRecoveryDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::RecoveryData>> PrepareAsyncGetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::RecoveryData>>(PrepareAsyncGetRecoveryDataRaw(context, request, cq));
    }
    // 停止接受新请求（恢复模式）
    virtual ::grpc::Status Stop(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::witness::StopReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::StopReply>> AsyncStop(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::StopReply>>(AsyncStopRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::StopReply>> PrepareAsyncStop(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::StopReply>>(PrepareAsyncStopRaw(context, request, cq));
    }
    // 重置 Witness 为新的 Master
    virtual ::grpc::Status Reset(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::witness::ResetReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::ResetReply>> AsyncReset(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::ResetReply>>(AsyncResetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::ResetReply>> PrepareAsyncReset(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::ResetReply>>(PrepareAsyncResetRaw(context, request, cq));
    }
    // 获取 Witness 状态
    virtual ::grpc::Status GetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::witness::StatusReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::StatusReply>> AsyncGetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::StatusReply>>(AsyncGetStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::StatusReply>> PrepareAsyncGetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::witness::StatusReply>>(PrepareAsyncGetStatusRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 客户端记录请求到 Witness
      virtual void Record(::grpc::ClientContext* context, const ::witness::RecordRequest* request, ::witness::RecordReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Record(::grpc::ClientContext* context, const ::witness::RecordRequest* request, ::witness::RecordReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Master 垃圾回收已同步的请求
      virtual void GarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest* request, ::witness::GCReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest* request, ::witness::GCReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 恢复时获取所有记录的请求
      virtual void GetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest* request, ::witness::RecoveryData* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest* request, ::witness::RecoveryData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 停止接受新请求（恢复模式）
      virtual void Stop(::grpc::ClientContext* context, const ::witness::StopRequest* request, ::witness::StopReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Stop(::grpc::ClientContext* context, const ::witness::StopRequest* request, ::witness::StopReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 重置 Witness 为新的 Master
      virtual void Reset(::grpc::ClientContext* context, const ::witness::ResetRequest* request, ::witness::ResetReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Reset(::grpc::ClientContext* context, const ::witness::ResetRequest* request, ::witness::ResetReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 获取 Witness 状态
      virtual void GetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest* request, ::witness::StatusReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest* request, ::witness::StatusReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::witness::RecordReply>* AsyncRecordRaw(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::witness::RecordReply>* PrepareAsyncRecordRaw(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::witness::GCReply>* AsyncGarbageCollectRaw(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::witness::GCReply>* PrepareAsyncGarbageCollectRaw(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::witness::RecoveryData>* AsyncGetRecoveryDataRaw(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::witness::RecoveryData>* PrepareAsyncGetRecoveryDataRaw(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::witness::StopReply>* AsyncStopRaw(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::witness::StopReply>* PrepareAsyncStopRaw(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::witness::ResetReply>* AsyncResetRaw(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::witness::ResetReply>* PrepareAsyncResetRaw(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::witness::StatusReply>* AsyncGetStatusRaw(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::witness::StatusReply>* PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Record(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::witness::RecordReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::RecordReply>> AsyncRecord(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::RecordReply>>(AsyncRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::RecordReply>> PrepareAsyncRecord(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::RecordReply>>(PrepareAsyncRecordRaw(context, request, cq));
    }
    ::grpc::Status GarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::witness::GCReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::GCReply>> AsyncGarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::GCReply>>(AsyncGarbageCollectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::GCReply>> PrepareAsyncGarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::GCReply>>(PrepareAsyncGarbageCollectRaw(context, request, cq));
    }
    ::grpc::Status GetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::witness::RecoveryData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::RecoveryData>> AsyncGetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::RecoveryData>>(AsyncGetRecoveryDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::RecoveryData>> PrepareAsyncGetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::RecoveryData>>(PrepareAsyncGetRecoveryDataRaw(context, request, cq));
    }
    ::grpc::Status Stop(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::witness::StopReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::StopReply>> AsyncStop(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::StopReply>>(AsyncStopRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::StopReply>> PrepareAsyncStop(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::StopReply>>(PrepareAsyncStopRaw(context, request, cq));
    }
    ::grpc::Status Reset(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::witness::ResetReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::ResetReply>> AsyncReset(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::ResetReply>>(AsyncResetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::ResetReply>> PrepareAsyncReset(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::ResetReply>>(PrepareAsyncResetRaw(context, request, cq));
    }
    ::grpc::Status GetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::witness::StatusReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::StatusReply>> AsyncGetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::StatusReply>>(AsyncGetStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::StatusReply>> PrepareAsyncGetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::witness::StatusReply>>(PrepareAsyncGetStatusRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Record(::grpc::ClientContext* context, const ::witness::RecordRequest* request, ::witness::RecordReply* response, std::function<void(::grpc::Status)>) override;
      void Record(::grpc::ClientContext* context, const ::witness::RecordRequest* request, ::witness::RecordReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest* request, ::witness::GCReply* response, std::function<void(::grpc::Status)>) override;
      void GarbageCollect(::grpc::ClientContext* context, const ::witness::GCRequest* request, ::witness::GCReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest* request, ::witness::RecoveryData* response, std::function<void(::grpc::Status)>) override;
      void GetRecoveryData(::grpc::ClientContext* context, const ::witness::RecoveryRequest* request, ::witness::RecoveryData* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Stop(::grpc::ClientContext* context, const ::witness::StopRequest* request, ::witness::StopReply* response, std::function<void(::grpc::Status)>) override;
      void Stop(::grpc::ClientContext* context, const ::witness::StopRequest* request, ::witness::StopReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Reset(::grpc::ClientContext* context, const ::witness::ResetRequest* request, ::witness::ResetReply* response, std::function<void(::grpc::Status)>) override;
      void Reset(::grpc::ClientContext* context, const ::witness::ResetRequest* request, ::witness::ResetReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest* request, ::witness::StatusReply* response, std::function<void(::grpc::Status)>) override;
      void GetStatus(::grpc::ClientContext* context, const ::witness::StatusRequest* request, ::witness::StatusReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::witness::RecordReply>* AsyncRecordRaw(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::witness::RecordReply>* PrepareAsyncRecordRaw(::grpc::ClientContext* context, const ::witness::RecordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::witness::GCReply>* AsyncGarbageCollectRaw(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::witness::GCReply>* PrepareAsyncGarbageCollectRaw(::grpc::ClientContext* context, const ::witness::GCRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::witness::RecoveryData>* AsyncGetRecoveryDataRaw(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::witness::RecoveryData>* PrepareAsyncGetRecoveryDataRaw(::grpc::ClientContext* context, const ::witness::RecoveryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::witness::StopReply>* AsyncStopRaw(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::witness::StopReply>* PrepareAsyncStopRaw(::grpc::ClientContext* context, const ::witness::StopRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::witness::ResetReply>* AsyncResetRaw(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::witness::ResetReply>* PrepareAsyncResetRaw(::grpc::ClientContext* context, const ::witness::ResetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::witness::StatusReply>* AsyncGetStatusRaw(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::witness::StatusReply>* PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::witness::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Record_;
    const ::grpc::internal::RpcMethod rpcmethod_GarbageCollect_;
    const ::grpc::internal::RpcMethod rpcmethod_GetRecoveryData_;
    const ::grpc::internal::RpcMethod rpcmethod_Stop_;
    const ::grpc::internal::RpcMethod rpcmethod_Reset_;
    const ::grpc::internal::RpcMethod rpcmethod_GetStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 客户端记录请求到 Witness
    virtual ::grpc::Status Record(::grpc::ServerContext* context, const ::witness::RecordRequest* request, ::witness::RecordReply* response);
    // Master 垃圾回收已同步的请求
    virtual ::grpc::Status GarbageCollect(::grpc::ServerContext* context, const ::witness::GCRequest* request, ::witness::GCReply* response);
    // 恢复时获取所有记录的请求
    virtual ::grpc::Status GetRecoveryData(::grpc::ServerContext* context, const ::witness::RecoveryRequest* request, ::witness::RecoveryData* response);
    // 停止接受新请求（恢复模式）
    virtual ::grpc::Status Stop(::grpc::ServerContext* context, const ::witness::StopRequest* request, ::witness::StopReply* response);
    // 重置 Witness 为新的 Master
    virtual ::grpc::Status Reset(::grpc::ServerContext* context, const ::witness::ResetRequest* request, ::witness::ResetReply* response);
    // 获取 Witness 状态
    virtual ::grpc::Status GetStatus(::grpc::ServerContext* context, const ::witness::StatusRequest* request, ::witness::StatusReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Record : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Record() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Record() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Record(::grpc::ServerContext* /*context*/, const ::witness::RecordRequest* /*request*/, ::witness::RecordReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecord(::grpc::ServerContext* context, ::witness::RecordRequest* request, ::grpc::ServerAsyncResponseWriter< ::witness::RecordReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GarbageCollect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GarbageCollect() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GarbageCollect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GarbageCollect(::grpc::ServerContext* /*context*/, const ::witness::GCRequest* /*request*/, ::witness::GCReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGarbageCollect(::grpc::ServerContext* context, ::witness::GCRequest* request, ::grpc::ServerAsyncResponseWriter< ::witness::GCReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRecoveryData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRecoveryData() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetRecoveryData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecoveryData(::grpc::ServerContext* /*context*/, const ::witness::RecoveryRequest* /*request*/, ::witness::RecoveryData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRecoveryData(::grpc::ServerContext* context, ::witness::RecoveryRequest* request, ::grpc::ServerAsyncResponseWriter< ::witness::RecoveryData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Stop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Stop() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Stop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stop(::grpc::ServerContext* /*context*/, const ::witness::StopRequest* /*request*/, ::witness::StopReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStop(::grpc::ServerContext* context, ::witness::StopRequest* request, ::grpc::ServerAsyncResponseWriter< ::witness::StopReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Reset() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_Reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reset(::grpc::ServerContext* /*context*/, const ::witness::ResetRequest* /*request*/, ::witness::ResetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReset(::grpc::ServerContext* context, ::witness::ResetRequest* request, ::grpc::ServerAsyncResponseWriter< ::witness::ResetReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetStatus() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::witness::StatusRequest* /*request*/, ::witness::StatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStatus(::grpc::ServerContext* context, ::witness::StatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::witness::StatusReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Record<WithAsyncMethod_GarbageCollect<WithAsyncMethod_GetRecoveryData<WithAsyncMethod_Stop<WithAsyncMethod_Reset<WithAsyncMethod_GetStatus<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Record : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Record() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::witness::RecordRequest, ::witness::RecordReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::witness::RecordRequest* request, ::witness::RecordReply* response) { return this->Record(context, request, response); }));}
    void SetMessageAllocatorFor_Record(
        ::grpc::MessageAllocator< ::witness::RecordRequest, ::witness::RecordReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::witness::RecordRequest, ::witness::RecordReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Record() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Record(::grpc::ServerContext* /*context*/, const ::witness::RecordRequest* /*request*/, ::witness::RecordReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Record(
      ::grpc::CallbackServerContext* /*context*/, const ::witness::RecordRequest* /*request*/, ::witness::RecordReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GarbageCollect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GarbageCollect() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::witness::GCRequest, ::witness::GCReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::witness::GCRequest* request, ::witness::GCReply* response) { return this->GarbageCollect(context, request, response); }));}
    void SetMessageAllocatorFor_GarbageCollect(
        ::grpc::MessageAllocator< ::witness::GCRequest, ::witness::GCReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::witness::GCRequest, ::witness::GCReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GarbageCollect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GarbageCollect(::grpc::ServerContext* /*context*/, const ::witness::GCRequest* /*request*/, ::witness::GCReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GarbageCollect(
      ::grpc::CallbackServerContext* /*context*/, const ::witness::GCRequest* /*request*/, ::witness::GCReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetRecoveryData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRecoveryData() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::witness::RecoveryRequest, ::witness::RecoveryData>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::witness::RecoveryRequest* request, ::witness::RecoveryData* response) { return this->GetRecoveryData(context, request, response); }));}
    void SetMessageAllocatorFor_GetRecoveryData(
        ::grpc::MessageAllocator< ::witness::RecoveryRequest, ::witness::RecoveryData>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::witness::RecoveryRequest, ::witness::RecoveryData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRecoveryData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecoveryData(::grpc::ServerContext* /*context*/, const ::witness::RecoveryRequest* /*request*/, ::witness::RecoveryData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRecoveryData(
      ::grpc::CallbackServerContext* /*context*/, const ::witness::RecoveryRequest* /*request*/, ::witness::RecoveryData* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Stop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Stop() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::witness::StopRequest, ::witness::StopReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::witness::StopRequest* request, ::witness::StopReply* response) { return this->Stop(context, request, response); }));}
    void SetMessageAllocatorFor_Stop(
        ::grpc::MessageAllocator< ::witness::StopRequest, ::witness::StopReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::witness::StopRequest, ::witness::StopReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Stop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stop(::grpc::ServerContext* /*context*/, const ::witness::StopRequest* /*request*/, ::witness::StopReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Stop(
      ::grpc::CallbackServerContext* /*context*/, const ::witness::StopRequest* /*request*/, ::witness::StopReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Reset() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::witness::ResetRequest, ::witness::ResetReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::witness::ResetRequest* request, ::witness::ResetReply* response) { return this->Reset(context, request, response); }));}
    void SetMessageAllocatorFor_Reset(
        ::grpc::MessageAllocator< ::witness::ResetRequest, ::witness::ResetReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::witness::ResetRequest, ::witness::ResetReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reset(::grpc::ServerContext* /*context*/, const ::witness::ResetRequest* /*request*/, ::witness::ResetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Reset(
      ::grpc::CallbackServerContext* /*context*/, const ::witness::ResetRequest* /*request*/, ::witness::ResetReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetStatus() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::witness::StatusRequest, ::witness::StatusReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::witness::StatusRequest* request, ::witness::StatusReply* response) { return this->GetStatus(context, request, response); }));}
    void SetMessageAllocatorFor_GetStatus(
        ::grpc::MessageAllocator< ::witness::StatusRequest, ::witness::StatusReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::witness::StatusRequest, ::witness::StatusReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::witness::StatusRequest* /*request*/, ::witness::StatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::witness::StatusRequest* /*request*/, ::witness::StatusReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Record<WithCallbackMethod_GarbageCollect<WithCallbackMethod_GetRecoveryData<WithCallbackMethod_Stop<WithCallbackMethod_Reset<WithCallbackMethod_GetStatus<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Record : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Record() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Record() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Record(::grpc::ServerContext* /*context*/, const ::witness::RecordRequest* /*request*/, ::witness::RecordReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GarbageCollect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GarbageCollect() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GarbageCollect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GarbageCollect(::grpc::ServerContext* /*context*/, const ::witness::GCRequest* /*request*/, ::witness::GCReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetRecoveryData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRecoveryData() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetRecoveryData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecoveryData(::grpc::ServerContext* /*context*/, const ::witness::RecoveryRequest* /*request*/, ::witness::RecoveryData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Stop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Stop() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Stop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stop(::grpc::ServerContext* /*context*/, const ::witness::StopRequest* /*request*/, ::witness::StopReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Reset() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_Reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reset(::grpc::ServerContext* /*context*/, const ::witness::ResetRequest* /*request*/, ::witness::ResetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetStatus() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::witness::StatusRequest* /*request*/, ::witness::StatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Record : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Record() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Record() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Record(::grpc::ServerContext* /*context*/, const ::witness::RecordRequest* /*request*/, ::witness::RecordReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecord(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GarbageCollect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GarbageCollect() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GarbageCollect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GarbageCollect(::grpc::ServerContext* /*context*/, const ::witness::GCRequest* /*request*/, ::witness::GCReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGarbageCollect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRecoveryData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRecoveryData() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetRecoveryData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecoveryData(::grpc::ServerContext* /*context*/, const ::witness::RecoveryRequest* /*request*/, ::witness::RecoveryData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRecoveryData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Stop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Stop() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Stop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stop(::grpc::ServerContext* /*context*/, const ::witness::StopRequest* /*request*/, ::witness::StopReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStop(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Reset() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_Reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reset(::grpc::ServerContext* /*context*/, const ::witness::ResetRequest* /*request*/, ::witness::ResetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReset(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetStatus() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::witness::StatusRequest* /*request*/, ::witness::StatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Record : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Record() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Record(context, request, response); }));
    }
    ~WithRawCallbackMethod_Record() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Record(::grpc::ServerContext* /*context*/, const ::witness::RecordRequest* /*request*/, ::witness::RecordReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Record(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GarbageCollect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GarbageCollect() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GarbageCollect(context, request, response); }));
    }
    ~WithRawCallbackMethod_GarbageCollect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GarbageCollect(::grpc::ServerContext* /*context*/, const ::witness::GCRequest* /*request*/, ::witness::GCReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GarbageCollect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRecoveryData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRecoveryData() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRecoveryData(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRecoveryData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecoveryData(::grpc::ServerContext* /*context*/, const ::witness::RecoveryRequest* /*request*/, ::witness::RecoveryData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRecoveryData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Stop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Stop() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Stop(context, request, response); }));
    }
    ~WithRawCallbackMethod_Stop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stop(::grpc::ServerContext* /*context*/, const ::witness::StopRequest* /*request*/, ::witness::StopReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Stop(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Reset() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Reset(context, request, response); }));
    }
    ~WithRawCallbackMethod_Reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Reset(::grpc::ServerContext* /*context*/, const ::witness::ResetRequest* /*request*/, ::witness::ResetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Reset(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetStatus() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::witness::StatusRequest* /*request*/, ::witness::StatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Record : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Record() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::witness::RecordRequest, ::witness::RecordReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::witness::RecordRequest, ::witness::RecordReply>* streamer) {
                       return this->StreamedRecord(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Record() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Record(::grpc::ServerContext* /*context*/, const ::witness::RecordRequest* /*request*/, ::witness::RecordReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecord(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::witness::RecordRequest,::witness::RecordReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GarbageCollect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GarbageCollect() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::witness::GCRequest, ::witness::GCReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::witness::GCRequest, ::witness::GCReply>* streamer) {
                       return this->StreamedGarbageCollect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GarbageCollect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GarbageCollect(::grpc::ServerContext* /*context*/, const ::witness::GCRequest* /*request*/, ::witness::GCReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGarbageCollect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::witness::GCRequest,::witness::GCReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRecoveryData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRecoveryData() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::witness::RecoveryRequest, ::witness::RecoveryData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::witness::RecoveryRequest, ::witness::RecoveryData>* streamer) {
                       return this->StreamedGetRecoveryData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRecoveryData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRecoveryData(::grpc::ServerContext* /*context*/, const ::witness::RecoveryRequest* /*request*/, ::witness::RecoveryData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRecoveryData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::witness::RecoveryRequest,::witness::RecoveryData>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Stop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Stop() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::witness::StopRequest, ::witness::StopReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::witness::StopRequest, ::witness::StopReply>* streamer) {
                       return this->StreamedStop(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Stop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Stop(::grpc::ServerContext* /*context*/, const ::witness::StopRequest* /*request*/, ::witness::StopReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStop(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::witness::StopRequest,::witness::StopReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Reset() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::witness::ResetRequest, ::witness::ResetReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::witness::ResetRequest, ::witness::ResetReply>* streamer) {
                       return this->StreamedReset(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Reset(::grpc::ServerContext* /*context*/, const ::witness::ResetRequest* /*request*/, ::witness::ResetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReset(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::witness::ResetRequest,::witness::ResetReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetStatus() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::witness::StatusRequest, ::witness::StatusReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::witness::StatusRequest, ::witness::StatusReply>* streamer) {
                       return this->StreamedGetStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::witness::StatusRequest* /*request*/, ::witness::StatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::witness::StatusRequest,::witness::StatusReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Record<WithStreamedUnaryMethod_GarbageCollect<WithStreamedUnaryMethod_GetRecoveryData<WithStreamedUnaryMethod_Stop<WithStreamedUnaryMethod_Reset<WithStreamedUnaryMethod_GetStatus<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Record<WithStreamedUnaryMethod_GarbageCollect<WithStreamedUnaryMethod_GetRecoveryData<WithStreamedUnaryMethod_Stop<WithStreamedUnaryMethod_Reset<WithStreamedUnaryMethod_GetStatus<Service > > > > > > StreamedService;
};

}  // namespace witness


#endif  // GRPC_witness_2eproto__INCLUDED
